import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Link href="/parallel">parallel page</Link>
        <Link href="/parallel/settings">Settings page</Link>
        <Link href="/options/image">Image options</Link>
        </body>
    </html>
  );
}
